version: 2.1
jobs:
  init:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd infra/
            terraform init
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - infra/.terraform

  create_bucket:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create bucket to host Function Compute code
          command: |
            cd infra/
            terraform apply -target=alicloud_oss_bucket.serverless-code

  build_profile_function:
    docker:
      - image: circleci/python:3.6.4
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Build profile function
          command: |
            pip install --upgrade pip pipenv
            cd src/profile
            pipenv lock -r > requirements.txt
            pip install -t . -r requirements.txt
            zip -r profile-$CIRCLE_SHA1.zip .
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - src/profile/*.zip

  upload_profile_function:
    docker:
      - image: leonrodenburg/aliyun-cli:3.0.22
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Upload functions to OSS
          command: |
            export REGION=$ALICLOUD_REGION
            export ACCESS_KEY_ID=$ALICLOUD_ACCESS_KEY
            export ACCESS_KEY_SECRET=$ALICLOUD_SECRET_KEY
            aliyun oss cp src/profile/profile-$CIRCLE_SHA1.zip oss://$OSS_CODE_BUCKET/profile-$CIRCLE_SHA1.zip

  plan_infra:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create Terraform plan
          command: |
            cd infra/
            export TF_VAR_profile_oss_key=profile-$CIRCLE_SHA1.zip
            terraform plan -input=false -out tf.plan
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - infra/tf.plan

  apply_infra:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Apply Terraform plan
          command: |
            cd infra/
            terraform apply tf.plan

workflows:
  version: 2
  build-init-plan-apply:
    jobs:
      - init
      - create_bucket:
          requires:
            - init
      - build_profile_function:
          requires:
            - create_bucket
      - upload_profile_function:
          requires:
            - build_profile_function
      - plan_infra:
          requires:
            - upload_profile_function
      - apply_infra:
          requires:
            - plan_infra