version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.5
    steps:
      - checkout
      - run: cd infra/
      - run: terraform init
workflows:
  version: 2
  build_and_test:
    jobs:
      - build