version: 2.1
jobs:
  init:
    docker:
      - image: hashicorp/terraform:0.12.5
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd infra/
            terraform init
  plan:
    docker:
      - image: hashicorp/terraform:0.12.5
    steps:
      - checkout
      - run:
          name: Create Terraform plan
          command: |
            cd infra/
            export TF_VAR_access_key=$ALI_ACCESS_KEY
            export TF_VAR_secret_key=$ALI_SECRET_KEY
            terraform plan -input=false -out tf.plan
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - plan:
          requires:
            - build