version: 2.1
jobs:
  init:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: infra
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            terraform init
  plan:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: infra
    steps:
      - checkout
      - run:
          name: Create Terraform plan
          command: |
            export TF_VAR_access_key=$ALI_ACCESS_KEY
            export TF_VAR_secret_key=$ALI_SECRET_KEY
            terraform plan -input=false -out tf.plan
      - persist_to_workspace:
          root: .
          paths:
            - tf.plan
  apply:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: infra
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Apply Terraform plan
          command: |
            export TF_VAR_access_key=$ALI_ACCESS_KEY
            export TF_VAR_secret_key=$ALI_SECRET_KEY
            terraform apply tf.plan
workflows:
  version: 2
  init-plan-apply:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan