version: 2.1
jobs:
  init:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd infra/
            terraform init
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - infra/.terraform

  plan:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create Terraform plan
          command: |
            cd infra/
            terraform plan -input=false -out tf.plan
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - infra/tf.plan

  apply:
    docker:
      - image: hashicorp/terraform:0.12.5
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Apply Terraform plan
          command: |
            cd infra/
            terraform apply tf.plan

workflows:
  version: 2
  init-plan-apply:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan